### ISSUE TITLE
V2ray Core Path指的是可执行文件吗？

### ISSUE THREAD

**Issue by kslr** [v2ray/V2Ray-shell_alpha#1]
我下载的是v2ray_linux 无法选中其中的v2ray文件

![image](https://user-images.githubusercontent.com/5516323/34708362-3f20ffce-f54d-11e7-8f38-be69c008d367.png)

**Comment by 699ebe23** [comment]
图片中没有看到v2ray这个文件。文件可能在Linux下的QT显示与windows有区别。
先选v2ray.sig，然后再把 .sig后缀去掉试试。
