### ISSUE TITLE
这是怎么回事？ deepin 最新版本

### ISSUE THREAD

**Issue by joostshao** [v2ray/V2Ray-shell_alpha#3]
![_ _20180306155037](https://user-images.githubusercontent.com/3615951/37020265-2e0badda-2156-11e8-9b1c-e5d8fd695e6b.png)

**Comment by 699ebe23** [comment]
使用bridge.py文件启动程序，直接点确定就可以了。
还有几个步骤要做:
1. 在options->Preference中添加v2ray程序文件路径
2. Ctrl+n添加v2ray的json配置文件
3. 选中配置文件激活此选项，然后点击启动按钮

如果使用bridge.py启动程序并保存了配置。会在相应目录下会生成一个config.v2rayshell文件
