### ISSUE TITLE
v2ray-shell.pyw can not run 

### ISSUE THREAD

**Issue by Zhangxxl** [v2ray/V2Ray-shell_alpha#4]
Console print：
`
Traceback (most recent call last):
  File "./v2ray-shell.pyw", line 3, in <module>
    from tkinter import Tk, BOTH, Text, END
  File "/usr/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
`
my system is :
OS: Arch Linux 
Kernel: x86_64 Linux 4.17.2-1-ARCH
Shell: zsh 5.5.1

**Comment by 699ebe23** [comment]
try this command install tkinter package:
```bash
sudo pacman -S tk
```

solution url:  https://stackoverflow.com/questions/48504746/importerror-libtk8-6-so-cannot-open-shared-object-file-no-such-file-or-direct?answertab=votes#tab-top
