### ISSUE TITLE
no PyQt5 install

### ISSUE THREAD

**Issue by earthGavinLee** [v2ray/V2Ray-shell_alpha#5]
ubuntu 16.04.4 已经提示安装了 PyQt5.
运行提示错误
![2018-07-23 02-34-49](https://user-images.githubusercontent.com/8288083/43048867-6b994576-8e21-11e8-8a2a-24ba636a127c.png)
![2018-07-23 02-35-47](https://user-images.githubusercontent.com/8288083/43048871-7b1e3a56-8e21-11e8-91c2-1dfec6692fda.png)

**Comment by earthGavinLee** [comment]
upgrade ptrhon 3.6
 ./v2ray-shell.pyw 
Could not initialize GLX
Aborted

**Comment by 699ebe23** [comment]
有可能显卡驱动没有安装好。
试试下面的解决方案:
https://stackoverflow.com/questions/42291236/python-spyder-could-not-initialize-glx#

顺便也把protobuf安装下，后面有个还没有完成的模块会用到。
python3 -m pip install protobuf grpcio grpcio-tools --user -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

后期有时间计划改成setuptools的安装，这样会比较方便。

**Comment by earthGavinLee** [comment]
我的是6卡NVIDIA显卡矿机。驱动没有问题。用的是集成显卡做的输出。另外python3.5的问题能解决一下吗？pyqt5的问题能解决一下吗？
我的xorg.conf的配置如下
# nvidia-xconfig: X configuration file generated by nvidia-xconfig
# nvidia-xconfig:  version 396.18  (buildmeister@swio-display-x86-rhel47-02)  Fri Apr  6 00:58:07 PDT 2018

Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "Screen6"
    Screen      1  "Screen1" RightOf "Screen0"
    Screen      2  "Screen2" RightOf "Screen1"
    Screen      3  "Screen3" RightOf "Screen2"
    Screen      4  "Screen4" RightOf "Screen3"
    Screen      5  "Screen5" RightOf "Screen4"
    Screen      6  "Screen0" RightOf "Screen6"
    InputDevice    "Keyboard0" "CoreKeyboard"
    InputDevice    "Mouse0" "CorePointer"
EndSection

Section "Files"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Mouse0"
    Driver         "mouse"
    Option         "Protocol" "auto"
    Option         "Device" "/dev/psaux"
    Option         "Emulate3Buttons" "no"
    Option         "ZAxisMapping" "4 5"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Keyboard0"
    Driver         "kbd"
EndSection

Section "Monitor"
    Identifier     "Monitor0"
    VendorName     "Unknown"
    ModelName      "Unknown"
    HorizSync       28.0 - 33.0
    VertRefresh     43.0 - 72.0
    Option         "DPMS"
EndSection

Section "Monitor"
    Identifier     "Monitor1"
    VendorName     "Unknown"
    ModelName      "Unknown"
    HorizSync       28.0 - 33.0
    VertRefresh     43.0 - 72.0
    Option         "DPMS"
EndSection

Section "Monitor"
    Identifier     "Monitor2"
    VendorName     "Unknown"
    ModelName      "Unknown"
    HorizSync       28.0 - 33.0
    VertRefresh     43.0 - 72.0
    Option         "DPMS"
EndSection

Section "Monitor"
    Identifier     "Monitor3"
    VendorName     "Unknown"
    ModelName      "Unknown"
    HorizSync       28.0 - 33.0
    VertRefresh     43.0 - 72.0
    Option         "DPMS"
EndSection

Section "Monitor"
    Identifier     "Monitor4"
    VendorName     "Unknown"
    ModelName      "Unknown"
    HorizSync       28.0 - 33.0
    VertRefresh     43.0 - 72.0
    Option         "DPMS"
EndSection

Section "Monitor"
    Identifier     "Monitor5"
    VendorName     "Unknown"
    ModelName      "Unknown"
    HorizSync       28.0 - 33.0
    VertRefresh     43.0 - 72.0
    Option         "DPMS"
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce GTX 1060 3GB"
    BusID          "PCI:1:0:0"
EndSection

Section "Device"
    Identifier     "Device1"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce GTX 1060 3GB"
    BusID          "PCI:2:0:0"
EndSection

Section "Device"
    Identifier     "Device2"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce GTX 1060 3GB"
    BusID          "PCI:3:0:0"
EndSection

Section "Device"
    Identifier     "Device3"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce GTX 1060 3GB"
    BusID          "PCI:5:0:0"
EndSection

Section "Device"
    Identifier     "Device4"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce GTX 1060 3GB"
    BusID          "PCI:6:0:0"
EndSection

Section "Device"
    Identifier     "Device5"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce GTX 1060 3GB"
    BusID          "PCI:7:0:0"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    Option         "ProbeAllGpus" "True"
    Option         "AllowEmptyInitialConfiguration" "True"
    Option         "Coolbits" "31"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection

Section "Screen"
    Identifier     "Screen1"
    Device         "Device1"
    Monitor        "Monitor1"
    DefaultDepth    24
    Option         "ProbeAllGpus" "True"
    Option         "AllowEmptyInitialConfiguration" "True"
    Option         "Coolbits" "31"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection

Section "Screen"
    Identifier     "Screen2"
    Device         "Device2"
    Monitor        "Monitor2"
    DefaultDepth    24
    Option         "ProbeAllGpus" "True"
    Option         "AllowEmptyInitialConfiguration" "True"
    Option         "Coolbits" "31"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection

Section "Screen"
    Identifier     "Screen3"
    Device         "Device3"
    Monitor        "Monitor3"
    DefaultDepth    24
    Option         "ProbeAllGpus" "True"
    Option         "AllowEmptyInitialConfiguration" "True"
    Option         "Coolbits" "31"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection

Section "Screen"
    Identifier     "Screen4"
    Device         "Device4"
    Monitor        "Monitor4"
    DefaultDepth    24
    Option         "ProbeAllGpus" "True"
    Option         "AllowEmptyInitialConfiguration" "True"
    Option         "Coolbits" "31"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection

Section "Screen"
    Identifier     "Screen5"
    Device         "Device5"
    Monitor        "Monitor5"
    DefaultDepth    24
    Option         "ProbeAllGpus" "True"
    Option         "AllowEmptyInitialConfiguration" "True"
    Option         "Coolbits" "31"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection

Section "Monitor"
		Identifier     "Monitor6"
		VendorName     "Unknown"
		ModelName      "Unknown"
EndSection

Section "Device"
		Identifier     "Device6"
		Driver         "intel"
		VendorName     "iGPU"
		BoardName      "iGPU"
		BusID          "PCI:0:2:0"
EndSection

Section "Screen"
		Identifier     "Screen6"
		Device         "Device6"
		Monitor        "Monitor6"
		DefaultDepth    24
		SubSection     "Display"
		Depth       24
		EndSubSection
EndSection

**Comment by 699ebe23** [comment]
python3.5的问题
pyqt5 降级到PyQt5==5.9.2
推荐pyenv安装python3.6.4 再安装相应的pyqt5 (开发环境用的版本)

glx问题
用ldd /usr/bin/glxinfo查看显卡驱动安装信息 glxinfo安装sudo apt-get install mesa-utils
看libGL.so libGLX.so
https://devtalk.nvidia.com/default/topic/1023403/linux/could-not-initialize-glx-with-nvidia-384-66-on-ubuntu-16-04/

**Comment by earthGavinLee** [comment]
ldd /usr/bin/glxinfo
	linux-vdso.so.1 =>  (0x00007fffe32d2000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f62ee388000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f62ee04e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f62edc84000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f62eda80000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f62ed850000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f62ed582000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f62ed360000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f62ee62c000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f62ed14e000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f62ecf4a000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f62ecd44000)

使用后 export __GLX_VENDOR_LIBRARY_NAME=nvidia运行 glxinfo
name of display: :0
Error: couldn't find RGB GLX visual or fbconfig

**Comment by 699ebe23** [comment]
opengl的库没有使用nvidia的库。
备份好libGL.so libGLX.so
试试比较粗暴的把libGL.so libGLX.so软连接到/usr/bin/nvidia/对应的库中。

**Comment by earthGavinLee** [comment]
INTEL显卡和NVIDIA显卡同时使用QT5的设计也是进不去，只能关闭INTEL，用NVIDIA多显卡就好了。
能追加一个更新订阅源的功能吗？

**Comment by 699ebe23** [comment]
没太明白订阅源是指什么。如果是自动更新v2ray-core，配置里已有。
如果是源代码更新，暂时还不考虑。可以自行crontab增加。
